# Generated by Django 6.0.6 on 2026-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
