# Generated by Django 6.0.6 on 2026-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
