# Generated by Django 6.0.6 on 2026-07-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role_type',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='teacher_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
