# Generated by Django 6.0.6 on 2026-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_designation_studentprofile_role_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
