# Generated by Django 6.0.6 on 2026-07-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='followed_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
