# Generated by Django 6.0.6 on 2026-07-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='reset_otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reset_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
