# Generated by Django 6.0.6 on 2026-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentprofile_reset_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='branch',
        ),
    ]
