# Generated by Django 6.0.6 on 2026-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_studentprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='in_app_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
