# Generated by Django 6.0.6 on 2026-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_in_app_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='non_tech_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tech_score',
            field=models.IntegerField(default=0),
        ),
    ]
