# Generated by Django 6.0.6 on 2026-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentprofile_non_tech_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='teacher_role',
            new_name='faculty_role',
        ),
    ]
