# Generated by Django 6.0.6 on 2026-07-01 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('text_color', models.CharField(max_length=50)),
                ('card_bg', models.CharField(default='#ffffff', max_length=50)),
                ('border_color', models.CharField(default='#e5e7eb', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_themes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
