# Generated by Django 6.0.6 on 2026-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
