# Generated by Django 6.0.6 on 2026-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_post_event_date_post_last_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='event_day_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='reminder_sent_1d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='reminder_sent_2d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='reminder_sent_3d',
            field=models.BooleanField(default=False),
        ),
    ]
