# Generated by Django 6.0.6 on 2026-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_userinterest_event_day_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_tech',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
