# Generated by Django 6.0.6 on 2026-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_category_is_tech_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
