# Generated by Django 6.0.6 on 2026-07-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('comments', '0002_rename_text_comment_content_comment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment'),
        ),
    ]
