# Generated by Django 6.0.6 on 2026-07-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_commentreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
